// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_header.proto

#ifndef PROTOBUF_message_5fheader_2eproto__INCLUDED
#define PROTOBUF_message_5fheader_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace PS {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_message_5fheader_2eproto();
void protobuf_AssignDesc_message_5fheader_2eproto();
void protobuf_ShutdownFile_message_5fheader_2eproto();

class MessageHeader;

enum MessageHeader_PkgType {
  MessageHeader_PkgType_SEND = 0,
  MessageHeader_PkgType_ACK = 1
};
bool MessageHeader_PkgType_IsValid(int value);
const MessageHeader_PkgType MessageHeader_PkgType_PkgType_MIN = MessageHeader_PkgType_SEND;
const MessageHeader_PkgType MessageHeader_PkgType_PkgType_MAX = MessageHeader_PkgType_ACK;
const int MessageHeader_PkgType_PkgType_ARRAYSIZE = MessageHeader_PkgType_PkgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageHeader_PkgType_descriptor();
inline const ::std::string& MessageHeader_PkgType_Name(MessageHeader_PkgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageHeader_PkgType_descriptor(), value);
}
inline bool MessageHeader_PkgType_Parse(
    const ::std::string& name, MessageHeader_PkgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageHeader_PkgType>(
    MessageHeader_PkgType_descriptor(), name, value);
}
enum MessageHeader_MsgType {
  MessageHeader_MsgType_USER = 0,
  MessageHeader_MsgType_SYS = 1
};
bool MessageHeader_MsgType_IsValid(int value);
const MessageHeader_MsgType MessageHeader_MsgType_MsgType_MIN = MessageHeader_MsgType_USER;
const MessageHeader_MsgType MessageHeader_MsgType_MsgType_MAX = MessageHeader_MsgType_SYS;
const int MessageHeader_MsgType_MsgType_ARRAYSIZE = MessageHeader_MsgType_MsgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageHeader_MsgType_descriptor();
inline const ::std::string& MessageHeader_MsgType_Name(MessageHeader_MsgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageHeader_MsgType_descriptor(), value);
}
inline bool MessageHeader_MsgType_Parse(
    const ::std::string& name, MessageHeader_MsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageHeader_MsgType>(
    MessageHeader_MsgType_descriptor(), name, value);
}
// ===================================================================

class MessageHeader : public ::google::protobuf::Message {
 public:
  MessageHeader();
  virtual ~MessageHeader();

  MessageHeader(const MessageHeader& from);

  inline MessageHeader& operator=(const MessageHeader& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageHeader& default_instance();

  void Swap(MessageHeader* other);

  // implements Message ----------------------------------------------

  MessageHeader* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageHeader& from);
  void MergeFrom(const MessageHeader& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef MessageHeader_PkgType PkgType;
  static const PkgType SEND = MessageHeader_PkgType_SEND;
  static const PkgType ACK = MessageHeader_PkgType_ACK;
  static inline bool PkgType_IsValid(int value) {
    return MessageHeader_PkgType_IsValid(value);
  }
  static const PkgType PkgType_MIN =
    MessageHeader_PkgType_PkgType_MIN;
  static const PkgType PkgType_MAX =
    MessageHeader_PkgType_PkgType_MAX;
  static const int PkgType_ARRAYSIZE =
    MessageHeader_PkgType_PkgType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  PkgType_descriptor() {
    return MessageHeader_PkgType_descriptor();
  }
  static inline const ::std::string& PkgType_Name(PkgType value) {
    return MessageHeader_PkgType_Name(value);
  }
  static inline bool PkgType_Parse(const ::std::string& name,
      PkgType* value) {
    return MessageHeader_PkgType_Parse(name, value);
  }

  typedef MessageHeader_MsgType MsgType;
  static const MsgType USER = MessageHeader_MsgType_USER;
  static const MsgType SYS = MessageHeader_MsgType_SYS;
  static inline bool MsgType_IsValid(int value) {
    return MessageHeader_MsgType_IsValid(value);
  }
  static const MsgType MsgType_MIN =
    MessageHeader_MsgType_MsgType_MIN;
  static const MsgType MsgType_MAX =
    MessageHeader_MsgType_MsgType_MAX;
  static const int MsgType_ARRAYSIZE =
    MessageHeader_MsgType_MsgType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MsgType_descriptor() {
    return MessageHeader_MsgType_descriptor();
  }
  static inline const ::std::string& MsgType_Name(MsgType value) {
    return MessageHeader_MsgType_Name(value);
  }
  static inline bool MsgType_Parse(const ::std::string& name,
      MsgType* value) {
    return MessageHeader_MsgType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string from_id = 1;
  inline bool has_from_id() const;
  inline void clear_from_id();
  static const int kFromIdFieldNumber = 1;
  inline const ::std::string& from_id() const;
  inline void set_from_id(const ::std::string& value);
  inline void set_from_id(const char* value);
  inline void set_from_id(const char* value, size_t size);
  inline ::std::string* mutable_from_id();
  inline ::std::string* release_from_id();
  inline void set_allocated_from_id(::std::string* from_id);

  // optional string from_ip = 2;
  inline bool has_from_ip() const;
  inline void clear_from_ip();
  static const int kFromIpFieldNumber = 2;
  inline const ::std::string& from_ip() const;
  inline void set_from_ip(const ::std::string& value);
  inline void set_from_ip(const char* value);
  inline void set_from_ip(const char* value, size_t size);
  inline ::std::string* mutable_from_ip();
  inline ::std::string* release_from_ip();
  inline void set_allocated_from_ip(::std::string* from_ip);

  // optional int32 from_port = 3;
  inline bool has_from_port() const;
  inline void clear_from_port();
  static const int kFromPortFieldNumber = 3;
  inline ::google::protobuf::int32 from_port() const;
  inline void set_from_port(::google::protobuf::int32 value);

  // required string to_id = 4;
  inline bool has_to_id() const;
  inline void clear_to_id();
  static const int kToIdFieldNumber = 4;
  inline const ::std::string& to_id() const;
  inline void set_to_id(const ::std::string& value);
  inline void set_to_id(const char* value);
  inline void set_to_id(const char* value, size_t size);
  inline ::std::string* mutable_to_id();
  inline ::std::string* release_to_id();
  inline void set_allocated_to_id(::std::string* to_id);

  // required string to_ip = 5;
  inline bool has_to_ip() const;
  inline void clear_to_ip();
  static const int kToIpFieldNumber = 5;
  inline const ::std::string& to_ip() const;
  inline void set_to_ip(const ::std::string& value);
  inline void set_to_ip(const char* value);
  inline void set_to_ip(const char* value, size_t size);
  inline ::std::string* mutable_to_ip();
  inline ::std::string* release_to_ip();
  inline void set_allocated_to_ip(::std::string* to_ip);

  // required int32 to_port = 6;
  inline bool has_to_port() const;
  inline void clear_to_port();
  static const int kToPortFieldNumber = 6;
  inline ::google::protobuf::int32 to_port() const;
  inline void set_to_port(::google::protobuf::int32 value);

  // required .PS.MessageHeader.PkgType pkg_type = 7;
  inline bool has_pkg_type() const;
  inline void clear_pkg_type();
  static const int kPkgTypeFieldNumber = 7;
  inline ::PS::MessageHeader_PkgType pkg_type() const;
  inline void set_pkg_type(::PS::MessageHeader_PkgType value);

  // required .PS.MessageHeader.MsgType msg_type = 8;
  inline bool has_msg_type() const;
  inline void clear_msg_type();
  static const int kMsgTypeFieldNumber = 8;
  inline ::PS::MessageHeader_MsgType msg_type() const;
  inline void set_msg_type(::PS::MessageHeader_MsgType value);

  // @@protoc_insertion_point(class_scope:PS.MessageHeader)
 private:
  inline void set_has_from_id();
  inline void clear_has_from_id();
  inline void set_has_from_ip();
  inline void clear_has_from_ip();
  inline void set_has_from_port();
  inline void clear_has_from_port();
  inline void set_has_to_id();
  inline void clear_has_to_id();
  inline void set_has_to_ip();
  inline void clear_has_to_ip();
  inline void set_has_to_port();
  inline void clear_has_to_port();
  inline void set_has_pkg_type();
  inline void clear_has_pkg_type();
  inline void set_has_msg_type();
  inline void clear_has_msg_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* from_id_;
  ::std::string* from_ip_;
  ::std::string* to_id_;
  ::google::protobuf::int32 from_port_;
  ::google::protobuf::int32 to_port_;
  ::std::string* to_ip_;
  int pkg_type_;
  int msg_type_;
  friend void  protobuf_AddDesc_message_5fheader_2eproto();
  friend void protobuf_AssignDesc_message_5fheader_2eproto();
  friend void protobuf_ShutdownFile_message_5fheader_2eproto();

  void InitAsDefaultInstance();
  static MessageHeader* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageHeader

// optional string from_id = 1;
inline bool MessageHeader::has_from_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageHeader::set_has_from_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageHeader::clear_has_from_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageHeader::clear_from_id() {
  if (from_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_id_->clear();
  }
  clear_has_from_id();
}
inline const ::std::string& MessageHeader::from_id() const {
  // @@protoc_insertion_point(field_get:PS.MessageHeader.from_id)
  return *from_id_;
}
inline void MessageHeader::set_from_id(const ::std::string& value) {
  set_has_from_id();
  if (from_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_id_ = new ::std::string;
  }
  from_id_->assign(value);
  // @@protoc_insertion_point(field_set:PS.MessageHeader.from_id)
}
inline void MessageHeader::set_from_id(const char* value) {
  set_has_from_id();
  if (from_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_id_ = new ::std::string;
  }
  from_id_->assign(value);
  // @@protoc_insertion_point(field_set_char:PS.MessageHeader.from_id)
}
inline void MessageHeader::set_from_id(const char* value, size_t size) {
  set_has_from_id();
  if (from_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_id_ = new ::std::string;
  }
  from_id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:PS.MessageHeader.from_id)
}
inline ::std::string* MessageHeader::mutable_from_id() {
  set_has_from_id();
  if (from_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:PS.MessageHeader.from_id)
  return from_id_;
}
inline ::std::string* MessageHeader::release_from_id() {
  clear_has_from_id();
  if (from_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = from_id_;
    from_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageHeader::set_allocated_from_id(::std::string* from_id) {
  if (from_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete from_id_;
  }
  if (from_id) {
    set_has_from_id();
    from_id_ = from_id;
  } else {
    clear_has_from_id();
    from_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:PS.MessageHeader.from_id)
}

// optional string from_ip = 2;
inline bool MessageHeader::has_from_ip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageHeader::set_has_from_ip() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageHeader::clear_has_from_ip() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageHeader::clear_from_ip() {
  if (from_ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_ip_->clear();
  }
  clear_has_from_ip();
}
inline const ::std::string& MessageHeader::from_ip() const {
  // @@protoc_insertion_point(field_get:PS.MessageHeader.from_ip)
  return *from_ip_;
}
inline void MessageHeader::set_from_ip(const ::std::string& value) {
  set_has_from_ip();
  if (from_ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_ip_ = new ::std::string;
  }
  from_ip_->assign(value);
  // @@protoc_insertion_point(field_set:PS.MessageHeader.from_ip)
}
inline void MessageHeader::set_from_ip(const char* value) {
  set_has_from_ip();
  if (from_ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_ip_ = new ::std::string;
  }
  from_ip_->assign(value);
  // @@protoc_insertion_point(field_set_char:PS.MessageHeader.from_ip)
}
inline void MessageHeader::set_from_ip(const char* value, size_t size) {
  set_has_from_ip();
  if (from_ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_ip_ = new ::std::string;
  }
  from_ip_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:PS.MessageHeader.from_ip)
}
inline ::std::string* MessageHeader::mutable_from_ip() {
  set_has_from_ip();
  if (from_ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_ip_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:PS.MessageHeader.from_ip)
  return from_ip_;
}
inline ::std::string* MessageHeader::release_from_ip() {
  clear_has_from_ip();
  if (from_ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = from_ip_;
    from_ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageHeader::set_allocated_from_ip(::std::string* from_ip) {
  if (from_ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete from_ip_;
  }
  if (from_ip) {
    set_has_from_ip();
    from_ip_ = from_ip;
  } else {
    clear_has_from_ip();
    from_ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:PS.MessageHeader.from_ip)
}

// optional int32 from_port = 3;
inline bool MessageHeader::has_from_port() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageHeader::set_has_from_port() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageHeader::clear_has_from_port() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageHeader::clear_from_port() {
  from_port_ = 0;
  clear_has_from_port();
}
inline ::google::protobuf::int32 MessageHeader::from_port() const {
  // @@protoc_insertion_point(field_get:PS.MessageHeader.from_port)
  return from_port_;
}
inline void MessageHeader::set_from_port(::google::protobuf::int32 value) {
  set_has_from_port();
  from_port_ = value;
  // @@protoc_insertion_point(field_set:PS.MessageHeader.from_port)
}

// required string to_id = 4;
inline bool MessageHeader::has_to_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MessageHeader::set_has_to_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MessageHeader::clear_has_to_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MessageHeader::clear_to_id() {
  if (to_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_id_->clear();
  }
  clear_has_to_id();
}
inline const ::std::string& MessageHeader::to_id() const {
  // @@protoc_insertion_point(field_get:PS.MessageHeader.to_id)
  return *to_id_;
}
inline void MessageHeader::set_to_id(const ::std::string& value) {
  set_has_to_id();
  if (to_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_id_ = new ::std::string;
  }
  to_id_->assign(value);
  // @@protoc_insertion_point(field_set:PS.MessageHeader.to_id)
}
inline void MessageHeader::set_to_id(const char* value) {
  set_has_to_id();
  if (to_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_id_ = new ::std::string;
  }
  to_id_->assign(value);
  // @@protoc_insertion_point(field_set_char:PS.MessageHeader.to_id)
}
inline void MessageHeader::set_to_id(const char* value, size_t size) {
  set_has_to_id();
  if (to_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_id_ = new ::std::string;
  }
  to_id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:PS.MessageHeader.to_id)
}
inline ::std::string* MessageHeader::mutable_to_id() {
  set_has_to_id();
  if (to_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:PS.MessageHeader.to_id)
  return to_id_;
}
inline ::std::string* MessageHeader::release_to_id() {
  clear_has_to_id();
  if (to_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = to_id_;
    to_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageHeader::set_allocated_to_id(::std::string* to_id) {
  if (to_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete to_id_;
  }
  if (to_id) {
    set_has_to_id();
    to_id_ = to_id;
  } else {
    clear_has_to_id();
    to_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:PS.MessageHeader.to_id)
}

// required string to_ip = 5;
inline bool MessageHeader::has_to_ip() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MessageHeader::set_has_to_ip() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MessageHeader::clear_has_to_ip() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MessageHeader::clear_to_ip() {
  if (to_ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_ip_->clear();
  }
  clear_has_to_ip();
}
inline const ::std::string& MessageHeader::to_ip() const {
  // @@protoc_insertion_point(field_get:PS.MessageHeader.to_ip)
  return *to_ip_;
}
inline void MessageHeader::set_to_ip(const ::std::string& value) {
  set_has_to_ip();
  if (to_ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_ip_ = new ::std::string;
  }
  to_ip_->assign(value);
  // @@protoc_insertion_point(field_set:PS.MessageHeader.to_ip)
}
inline void MessageHeader::set_to_ip(const char* value) {
  set_has_to_ip();
  if (to_ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_ip_ = new ::std::string;
  }
  to_ip_->assign(value);
  // @@protoc_insertion_point(field_set_char:PS.MessageHeader.to_ip)
}
inline void MessageHeader::set_to_ip(const char* value, size_t size) {
  set_has_to_ip();
  if (to_ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_ip_ = new ::std::string;
  }
  to_ip_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:PS.MessageHeader.to_ip)
}
inline ::std::string* MessageHeader::mutable_to_ip() {
  set_has_to_ip();
  if (to_ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_ip_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:PS.MessageHeader.to_ip)
  return to_ip_;
}
inline ::std::string* MessageHeader::release_to_ip() {
  clear_has_to_ip();
  if (to_ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = to_ip_;
    to_ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageHeader::set_allocated_to_ip(::std::string* to_ip) {
  if (to_ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete to_ip_;
  }
  if (to_ip) {
    set_has_to_ip();
    to_ip_ = to_ip;
  } else {
    clear_has_to_ip();
    to_ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:PS.MessageHeader.to_ip)
}

// required int32 to_port = 6;
inline bool MessageHeader::has_to_port() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MessageHeader::set_has_to_port() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MessageHeader::clear_has_to_port() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MessageHeader::clear_to_port() {
  to_port_ = 0;
  clear_has_to_port();
}
inline ::google::protobuf::int32 MessageHeader::to_port() const {
  // @@protoc_insertion_point(field_get:PS.MessageHeader.to_port)
  return to_port_;
}
inline void MessageHeader::set_to_port(::google::protobuf::int32 value) {
  set_has_to_port();
  to_port_ = value;
  // @@protoc_insertion_point(field_set:PS.MessageHeader.to_port)
}

// required .PS.MessageHeader.PkgType pkg_type = 7;
inline bool MessageHeader::has_pkg_type() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MessageHeader::set_has_pkg_type() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MessageHeader::clear_has_pkg_type() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MessageHeader::clear_pkg_type() {
  pkg_type_ = 0;
  clear_has_pkg_type();
}
inline ::PS::MessageHeader_PkgType MessageHeader::pkg_type() const {
  // @@protoc_insertion_point(field_get:PS.MessageHeader.pkg_type)
  return static_cast< ::PS::MessageHeader_PkgType >(pkg_type_);
}
inline void MessageHeader::set_pkg_type(::PS::MessageHeader_PkgType value) {
  assert(::PS::MessageHeader_PkgType_IsValid(value));
  set_has_pkg_type();
  pkg_type_ = value;
  // @@protoc_insertion_point(field_set:PS.MessageHeader.pkg_type)
}

// required .PS.MessageHeader.MsgType msg_type = 8;
inline bool MessageHeader::has_msg_type() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void MessageHeader::set_has_msg_type() {
  _has_bits_[0] |= 0x00000080u;
}
inline void MessageHeader::clear_has_msg_type() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void MessageHeader::clear_msg_type() {
  msg_type_ = 0;
  clear_has_msg_type();
}
inline ::PS::MessageHeader_MsgType MessageHeader::msg_type() const {
  // @@protoc_insertion_point(field_get:PS.MessageHeader.msg_type)
  return static_cast< ::PS::MessageHeader_MsgType >(msg_type_);
}
inline void MessageHeader::set_msg_type(::PS::MessageHeader_MsgType value) {
  assert(::PS::MessageHeader_MsgType_IsValid(value));
  set_has_msg_type();
  msg_type_ = value;
  // @@protoc_insertion_point(field_set:PS.MessageHeader.msg_type)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PS

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::PS::MessageHeader_PkgType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PS::MessageHeader_PkgType>() {
  return ::PS::MessageHeader_PkgType_descriptor();
}
template <> struct is_proto_enum< ::PS::MessageHeader_MsgType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PS::MessageHeader_MsgType>() {
  return ::PS::MessageHeader_MsgType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_5fheader_2eproto__INCLUDED
